In [5]:
# Update sklearn to prevent version mismatches
#!conda install scikit-learn
#!conda update scikit-learn
#!conda install joblib 
#!conda update joblib 

In [6]:
import pandas as pd

In [8]:
# Import the testing csvs 
testing_data = pd.read_csv('test_data.csv')
#testing_data = pd.read_csv('cumulative.csv')
#testing_data = testing_data.drop(columns=["rowid", "kepid", "kepoi_name", "kepler_name", "koi_pdisposition", "koi_score", "koi_tce_delivname"])
# Drop the null columns where all values are null
testing_data = testing_data.dropna(axis='columns', how='all')
# Drop the null rows
testing_data = testing_data.dropna()
testing_data.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CANDIDATE              0              0              0              0   
1       CONFIRMED              0              0              0              0   
2  FALSE POSITIVE              0              0              1              1   
3  FALSE POSITIVE              1              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   10.191547         0.000078        -0.000078    136.69755   
1    8.308653         0.000010        -0.000010    138.10788   
2    9.942219         0.000059        -0.000059    133.84961   
3    0.948952         0.000010        -0.000010    131.85772   
4   14.613478         0.000156        -0.000156    140.41368   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0           0.00647  ...             -74      4.049           0.013   
1           0.00102  ...             -80      4.485           0.077   
2           0.00532  ...            -155      4.434           0.126   
3           0.00821  ...            -232      3.666           0.304   
4           0.00701  ...            -136      4.242           0.125   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.015     1.684          0.107         -0.063  281.46173   
1          -0.033     0.849          0.040         -0.066  291.64090   
2          -0.273     0.917          0.269         -0.124  298.64505   
3          -0.076     3.067          0.461         -1.077  299.12161   
4          -0.125     1.314          0.244         -0.200  290.99527   

         dec  koi_kepmag  
0  46.789894      11.740  
1  41.241039      14.817  
2  42.089851      14.129  
3  41.424450      12.669  
4  45.192211      13.223  

[5 rows x 41 columns]

In [9]:
# Split the test data into X and y
y_test = testing_data["koi_disposition"]
X_test = testing_data.drop(columns=["koi_disposition"])

In [10]:
# scale the data if the student did
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_test= scaler.fit_transform(X_test)

C:\Users\tian\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [11]:
# set your x_test to match the same variables that the student chose. 
# Can copy/paste their feature selection code. Just be sure to set it to X_test
#X_test = X_test[[]]
#X_test = X_test.reshape(-1, 1)
print(X_test)


[[0.         0.         0.         ... 0.07357815 0.64692556 0.39114053]
 [0.         0.         0.         ... 0.53905974 0.28615251 0.70448065]
 [0.         0.         1.         ... 0.85935136 0.3413402  0.63441955]
 ...
 [0.         1.         0.         ... 0.74057483 0.45006823 0.71629328]
 [1.         0.         1.         ... 0.20474171 0.25334218 0.74725051]
 [0.         1.         1.         ... 0.68080267 0.1414541  0.78350305]]


# Testing

In [12]:
# load and score the student's model
import joblib
# update file name with student file
#filename = 'student_model.sav'
filename = 'logistic.sav'
loaded_model = joblib.load(filename)

result = loaded_model.score(X_test, y_test)
print(result)

0.43240159726183686


# Deep Learning Testing

In [13]:
# load and score the student's model
import joblib
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

# update file name with student file
filename = 'deep_learning.sav'
loaded_model = joblib.load(filename)

label_encoder = LabelEncoder()
label_encoder.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)

y_test_categorical = to_categorical(encoded_y_test)

encoded_predictions = loaded_model.predict_classes(X_test[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

# Take number correct over total to get "score" for grading
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Using TensorFlow backend.








Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Predicted classes: ['CONFIRMED' 'CONFIRMED' 'FALSE POSITIVE' 'FALSE POSITIVE' 'CANDIDATE'
 'CANDIDATE' 'CANDIDATE' 'FALSE POSITIVE' 'FALSE POSITIVE'
 'FALSE POSITIVE']
Actual Labels: ['CANDIDATE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE']
